version: "3.8"

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

volumes:
  grafana-data: